### ISSUE TITLE
Minor issues compiling from scratch

### ISSUE THREAD

**Issue by anidev** [VTAstrobotics/Autonomy-2017#1]
Wanted to test something, tried compiling from scratch and ran into these issues, not really a major thing unless you ever do a `catkin_make clean`. Just thought I'd document them somewhere for the future.

- `rowens_driver` does not depend on `robot_msgs_generate_messages_cpp`, so compiling fails because the messages haven't been generated yet
- The autonomous_control header includes the `Atest` message, which is never used and no longer exists in `robot_msgs`, so compiling fails there too. The include can just be removed from the header file.

**Comment by zfellone** [comment]
Fixed 4/17
